In [59]:
import numpy as np
import pandas as pd

In [60]:
df=pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [61]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [62]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [63]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [65]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['gender']=le.fit_transform(df['gender'])
df['cough']=le.fit_transform(df['cough'])
df['has_covid']=le.fit_transform(df['has_covid'])
df['city']=le.fit_transform(df['city'])

In [66]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [67]:
from sklearn.model_selection import train_test_split
X=df.drop(columns=['has_covid'])
y=df['has_covid']

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [69]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.75

In [71]:
import joblib
joblib.dump(model,'LogisticRegression.pkl')

['LogisticRegression.pkl']